name: date_time_calender
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  percent_indicator: ^2.1.1+1
  google_fonts: ^0.3.2
  intl: ^0.16.0


flutter:

  uses-material-design: true

  assets:
    - images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Kufam-Regular
       fonts:
         - asset: fonts/Kufam-Regular.ttf

     - family: Montserrat-Medium
       fonts:
         - asset: fonts/Montserrat-Medium.ttf